#ifndef PHPCPP_H
#define PHPCPP_H

#include <string.h>
#include <string>
#include <initializer_list>
#include <vector>
#include <memory>
#include <list>
#include <exception>
#include <map>
#include <set>
#include <functional>

#include "visibility.h"
#include "deprecated.h"
#include "noexcept.h"
#include "thread_local.h"
#include "platform.h"
#include "version.h"
#include "inivalue.h"
#include "ini.h"
#include "exception.h"
#include "fatalerror.h"
#include "streams.h"
#include "errors.h"
#include "type.h"
#include "hashparent.h"
#include "value.h"
#include "valueiterator.h"
#include "array.h"
#include "object.h"
#include "globals.h"
#include "argument.h"
#include "byval.h"
#include "byref.h"
#include "global.h"
#include "hashmember.h"
#include "super.h"
#include "parameters.h"
#include "modifiers.h"
#include "base.h"
#include "countable.h"
#include "arrayaccess.h"
#include "iterator.h"
#include "traversable.h"
#include "serializable.h"
#include "classtype.h"
#include "classbase.h"
#include "constant.h"
#include "interface.h"
#include "zendcallable.h"
#include "class.h"
#include "namespace.h"
#include "extension.h"
#include "call.h"
#include "script.h"
#include "file.h"
#include "function.h"

#endif // PHPCPP_H
